package tennis.modell;

/*-
 * #%L
 * TennisGyak
 * %%
 * Copyright (C) 2018 University of Debrecen
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * #L%
 */

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import tennis.Tennis;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URISyntaxException;
import java.time.LocalDate;

/**
 * A PDF generálását megvalósító osztály.
 *
 * @author adamberki97
 */
public class PdfGeneration {

    /**
     * A logger létrehozása a PdfGeneration classra.
     */
    private static final Logger LOG = LoggerFactory.getLogger(PdfGeneration.class);

    /**
     * PDF-et generál a project PDF packagebebe, booking.pdf néven.
     *
     * @param name : A név melyen foglalás történt.
     * @param date : Az időpont melyre a foglalás történt.
     * @param palyaszam : A lefoglalandó pálya száma.
     * @param ar   : A fizetendő összeg a foglalásért.
     * @param file : A save dialog segítségével kiválasztott file, mely a generált pdf lesz.
     * @throws java.net.URISyntaxException ha a PDF-et nem lehet létrehozni/ legenerálni.
     */
    public final void pdfGeneration(final String name, final String date, final int palyaszam, final int ar, final File file) throws URISyntaxException {
        Document document = new Document();

        try {

            PdfWriter.getInstance(document, new FileOutputStream(file));
            document.open();

            LOG.info("PDF generated!");

            Image image = Image.getInstance(getClass().getResource("/Pictures/tennisapp.png"));
            image.scaleToFit(300, 200);
            image.setAbsolutePosition(250f, 700f);
            document.add(image);

            document.add(new Paragraph("\n" + "Details of the reservation :"));

            document.add(new Paragraph("\n\n > Name: " + name));
            document.add(new Paragraph("\n > Reservation date: " + LocalDate.now()));
            document.add(new Paragraph("\n > Choosen date : " + date));
            document.add(new Paragraph("\n > Court : " + Integer.toString(palyaszam) + "."));
            document.add(new Paragraph("\n > Price : " + Integer.toString(ar)));

            document.add(new Paragraph("\n\n\n\n\n\n Thank you for your reservation!"));
            Chunk signature = new Chunk("\n Generated by the TennisApp 2000 application!");
            Paragraph base = new Paragraph(signature);
            document.add(base);

        } catch (DocumentException | IOException e) {
            LOG.error("The PDF can not be created!");
        }

        document.close();
    }
}
